# folder of origin: pytorch-3dunet1.8.2, 3DUnet_lightsheet_boundary

# Download test data from: https://osf.io/tn4xj/

# PATH_TO_BEST_CHECKPOINT
model_path: /home/dwalth/data/outputs/chpt-240221-0/last_checkpoint.pytorch
model:
  name: ResidualUNet3D
  # number of input channels to the model
  in_channels: 3
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'StandardPredictor'
loaders:
  # save predictions to output_dir
  output_dir: /home/dwalth/data/outputs/chpt-240226-1
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    file_paths:  # PATH_TO_TEST_DIR
      - /home/dwalth/scratch/datasets/dataset11.a.0/test/

    slice_builder:
      name: SliceBuilder
      # DW: patch originally [80, 170, 170]
      patch_shape: [120,720,320]
      # DW: stride originally [40, 90, 90]
      stride_shape: [14,11,57]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
